  version: '2'

  services:
    todo_container:
      image: mnamver/todo
      ports:
        - "9060:9060"
      depends_on:
        - "couchbase_container"
      restart: always

    couchbase_container:
      image: mnamver/couchbase
      ports:
        - "8091-8093:8091-8093"
        - "11210:11210"

